### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [spotify/NFHTTP#22]
Would you like to add more error handling for return values from functions like the following?
- [fseek](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator.") ⇒ [CachingClient::responseFromCacheItem](https://github.com/spotify/NFHTTP/blob/a99164a6df60947e20ec58fc05b4e39a34971819/source/CachingClient.cpp#L224)
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [RequestImplementation constructor](https://github.com/spotify/NFHTTP/blob/63210526176f2d7ce33a65ffe54c0fa31ac55632/source/RequestImplementation.cpp#L41)

**Comment by drubinstein** [comment]
Thanks for commenting and looking at NFHTTP!

`fseek` could probably use some better error reporting. I disagree on `malloc` and would instead prioritize #24

**Comment by alexhultman** [comment]
@drubinstein You're talking to a bot. It sends a bunch of identical bug reports to plenty of projects. I've had him banned for 2 years because of recurring spam of pedantic and very opinionated pointless changes. It's been doing that for years.

We should probably report this to GitHub

**Comment by alexhultman** [comment]
Here is mine: https://github.com/uNetworking/uSockets/issues/44

**Comment by drubinstein** [comment]
Thanks @alexhultman
