### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [spotify/NFHTTP#23]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
* [RequestImplementation destructor](https://github.com/spotify/NFHTTP/blob/63210526176f2d7ce33a65ffe54c0fa31ac55632/source/RequestImplementation.cpp#L67)
* [ResponseImplementation destructor](https://github.com/spotify/NFHTTP/blob/63210526176f2d7ce33a65ffe54c0fa31ac55632/source/ResponseImplementation.cpp#L75)

**Comment by drubinstein** [comment]
Thanks for opening this issue!

I'd rather remove the `malloc`s and `free`s and use types that implement RAII such as `std::vector` or `std::deque` if possible. I'm going to close this issue and create a new one instead about RAII.

**Comment by elfring** [comment]
I am curious then how the software development will be continued also for [the topic “Use RAII instead of manual memory management”](https://github.com/spotify/NFHTTP/issues/24 "Better memory management").
