### ISSUE TITLE
Please support python3 in  generate-version.py

### ISSUE THREAD

**Issue by MikeGitb** [spotify/NFHTTP#25]
I get some errors from `generate-version.py` when running cmake . 

From a quick glance, I'd suspect that this comes from the fact that the script assumes it is run with python2 and my default python version is 3. Python 2 is deprecated and will receive no support after end of 2019. Please make your python script compatible with python3.

**Comment by gazzyt** [comment]
I have provided pull request #34 to support Python 3.

**Comment by MikeGitb** [comment]
@gazzyt : Thank you very much
