### ISSUE TITLE
Breaks C++ Core Guideline R35

### ISSUE THREAD

**Issue by lenkite** [spotify/NFHTTP#28]
R.35: Take a shared_ptr<widget>& parameter to express that a function might reseat the shared pointer

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rr-sharedptrparam

I do not believe that  `[](const std::shared_ptr<nativeformat::http::Response> &response` makes sense as lambda callback.

**Comment by rLadia** [comment]
R.36: Take a const shared_ptr<widget>& parameter to express that it might retain a reference count to the object

Passing a shared_ptr by const reference allows the lambda to make a copy of the shared_ptr if needed, or to not make a copy and avoid the overhead of changing the reference count.
